apiVersion: apps/v1
kind: Deployment
metadata:
  name: practica-deployment
  labels:
    app: practica
spec:
  replicas: 3
  selector:
    matchLabels:
      app: practica
  template:
    metadata:
      labels:
        app: practica
    spec:
      containers:
        - name: prac-container
          #image: ms_practica_eks:1.0
          image: 928975674404.dkr.ecr.us-east-1.amazonaws.com/practice-repo:ms_practica_eks2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080